### ISSUE TITLE
Please check iobroker.js2fs with js-controller 2.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [soef/iobroker.js2fs#31]
Hi,

the new js-controller 2.0 will come into latest repository in the next days and we want to make sure that all adapters are working well. We already did a 2 weeks Beta test and so some adapter were aleady checked and some needed slight adjustments.

You can find more information in https://github.com/ioBroker/ioBroker.js-controller/issues/482 and in the ioBroker Forum. If you have more technical questions please write in the referenced issue or in the Developer thread please. General questions are best in the genral thread.

Please update your systems to js-controller 2.0 and check your adapter.

Please close this issue once you have checked your adapter or received successfull reports from users.

Thank you very much for your support. Please contact us in the other Threads or Forum on any question.

**Comment by eric2905** [comment]
Hi,

here the Log when starting the instance of js2fs:


host.iobroker01 | 2019-11-01 05:54:41.717 | info | Restart adapter system.adapter.js2fs.0 because enabled
-- | -- | -- | --
host.iobroker01 | 2019-11-01 05:54:41.717 | error | instance system.adapter.js2fs.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker01 | 2019-11-01 05:54:41.717 | error | Caught by controller[0]: at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
host.iobroker01 | 2019-11-01 05:54:41.717 | error | Caught by controller[0]: at startup (internal/bootstrap/node.js:283:19)
host.iobroker01 | 2019-11-01 05:54:41.717 | error | Caught by controller[0]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.iobroker01 | 2019-11-01 05:54:41.717 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iobroker01 | 2019-11-01 05:54:41.717 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js2fs/js2fs.js:79:20)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: ^
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: fns.adapter = fns.adapter(options);
host.iobroker01 | 2019-11-01 05:54:41.716 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
host.iobroker01 | 2019-11-01 05:54:41.521 | info | instance system.adapter.js2fs.0 started with pid 5306

**Comment by markus2701** [comment]
push
